"""Validation services — per-edit statistical checks (VAL-001 onward).

Currently exposes:
  - ``conformal_pid`` — Conformal-PID prediction-band check (VAL-001).
  - ``probe_ir`` — PROBE invalidation-rate check (VAL-002).
  - ``ynn_plausibility`` — yNN k-NN plausibility under DTW (VAL-003).
  - ``native_guide`` — Native-Guide proximity & sparsity (VAL-004).
  - ``coefficient_ci`` — Coefficient-CI z-score under stationary bootstrap (VAL-005).
  - ``stationarity`` — ADF + KPSS + Zivot-Andrews joint stationarity check (VAL-006).

Keep this package free of Flask / DB imports so the validators can be reused
inside the coordinator and offline calibration scripts.
"""
from app.services.validation.coefficient_ci import (
    DEFAULT_B,
    DEFAULT_Z_THRESHOLD,
    CoefficientCIConfig,
    CoefficientCIError,
    CoefficientCIResult,
    CoefficientCIValidator,
    politis_white_block_length,
    refit_blob,
    stationary_bootstrap,
)
from app.services.validation.conformal_pid import (
    BandCheckResult,
    ConformalCalibrationError,
    ConformalConfig,
    ConformalPIDValidator,
    Forecaster,
    ValidationResult,
)
from app.services.validation.native_guide import (
    DEFAULT_DTW_BAND,
    DEFAULT_EPS_PER_DIM,
    DEFAULT_PROXIMITY_PERCENTILE,
    DEFAULT_SPARSITY_THRESHOLD,
    METRIC_DTW,
    METRIC_EUCLIDEAN,
    METRIC_L1,
    NativeGuideError,
    NativeGuideResult,
    NativeGuideThresholds,
    compute_nun_distances,
    load_thresholds,
    native_guide_proximity,
    native_guide_sparsity,
    native_guide_validate,
    percentile_rank,
    save_thresholds,
    thresholds_from_distances,
)
from app.services.validation.probe_ir import (
    DEFAULT_MC_SAMPLES,
    DEFAULT_SIGMA,
    METHOD_LINEARISED,
    METHOD_MONTE_CARLO,
    TIER2_DEFAULT_SIGMA,
    ProbeIRResult,
    ProbeMethodError,
    ProbeModel,
    default_sigma_for_op,
    probe_invalidation_rate,
)
from app.services.validation.stationarity import (
    DEFAULT_BREAK_TOLERANCE,
    StationarityError,
    StationarityResult,
    VERDICT_INTRODUCED,
    VERDICT_NONSTATIONARY_PRESERVED,
    VERDICT_REDUCED,
    VERDICT_STATIONARY_PRESERVED,
    VERDICT_UNDETERMINED,
    joint_stationarity_check,
    whiten_residual,
)
from app.services.validation.ynn_plausibility import (
    DEFAULT_CANDIDATE_MULTIPLIER,
    DEFAULT_K,
    YnnConfig,
    YnnIndexError,
    YnnPlausibilityValidator,
    YnnResult,
    keogh_envelope,
    lb_keogh,
)

__all__ = [
    "BandCheckResult",
    "CoefficientCIConfig",
    "CoefficientCIError",
    "CoefficientCIResult",
    "CoefficientCIValidator",
    "ConformalCalibrationError",
    "ConformalConfig",
    "ConformalPIDValidator",
    "DEFAULT_B",
    "DEFAULT_BREAK_TOLERANCE",
    "DEFAULT_CANDIDATE_MULTIPLIER",
    "DEFAULT_DTW_BAND",
    "DEFAULT_EPS_PER_DIM",
    "DEFAULT_K",
    "DEFAULT_MC_SAMPLES",
    "DEFAULT_PROXIMITY_PERCENTILE",
    "DEFAULT_SIGMA",
    "DEFAULT_SPARSITY_THRESHOLD",
    "DEFAULT_Z_THRESHOLD",
    "Forecaster",
    "METHOD_LINEARISED",
    "METHOD_MONTE_CARLO",
    "METRIC_DTW",
    "METRIC_EUCLIDEAN",
    "METRIC_L1",
    "NativeGuideError",
    "NativeGuideResult",
    "NativeGuideThresholds",
    "ProbeIRResult",
    "ProbeMethodError",
    "ProbeModel",
    "StationarityError",
    "StationarityResult",
    "TIER2_DEFAULT_SIGMA",
    "VERDICT_INTRODUCED",
    "VERDICT_NONSTATIONARY_PRESERVED",
    "VERDICT_REDUCED",
    "VERDICT_STATIONARY_PRESERVED",
    "VERDICT_UNDETERMINED",
    "ValidationResult",
    "YnnConfig",
    "YnnIndexError",
    "YnnPlausibilityValidator",
    "YnnResult",
    "compute_nun_distances",
    "default_sigma_for_op",
    "joint_stationarity_check",
    "keogh_envelope",
    "lb_keogh",
    "load_thresholds",
    "native_guide_proximity",
    "native_guide_sparsity",
    "native_guide_validate",
    "percentile_rank",
    "politis_white_block_length",
    "probe_invalidation_rate",
    "refit_blob",
    "save_thresholds",
    "stationary_bootstrap",
    "thresholds_from_distances",
    "whiten_residual",
]
