"""Validation services — per-edit statistical checks (VAL-001 onward).

Currently exposes:
  - ``conformal_pid`` — Conformal-PID prediction-band check (VAL-001).
  - ``probe_ir`` — PROBE invalidation-rate check (VAL-002).
  - ``ynn_plausibility`` — yNN k-NN plausibility under DTW (VAL-003).
  - ``native_guide`` — Native-Guide proximity & sparsity (VAL-004).
  - ``coefficient_ci`` — Coefficient-CI z-score under stationary bootstrap (VAL-005).
  - ``stationarity`` — ADF + KPSS + Zivot-Andrews joint stationarity check (VAL-006).
  - ``conservation_significance`` — bootstrap CI + ratio + MMD on conservation residuals (VAL-007).
  - ``mmd_distshift`` — linear-time MMD distshift for replace_from_library (VAL-008).
  - ``coverage`` — session-level shape-vocabulary coverage tracker (VAL-010).
  - ``diversity`` — DPP log-det diversity of accepted CFs (VAL-011).
  - ``validity_rate`` — session-level validity-rate tracker (VAL-012).
  - ``cherry_picking`` — TS adaptation of the Hinns 2026 cherry-picking detector (VAL-013).
  - ``tip_engine`` — Lotse-style YAML-rule tip-generation engine (VAL-020).
  - ``iaaft`` — IAAFT surrogate test, slow path (VAL-030).
  - ``mbb`` — full moving-block bootstrap, slow path (VAL-031).

Keep this package free of Flask / DB imports so the validators can be reused
inside the coordinator and offline calibration scripts.
"""
from app.services.validation.cherry_picking import (
    DEFAULT_MIN_ACCEPTED,
    DEFAULT_N_SAMPLES,
    DEFAULT_TIP_SCORE_THRESHOLD,
    DEFAULT_UTILITY_WEIGHTS,
    AdmissibleCFSampler,
    CherryPickingDetector,
    CherryPickingError,
    CherryPickingScore,
    UtilityFn,
    default_utility_fn,
)
from app.services.validation.iaaft import (
    DEFAULT_MAX_ITER,
    DEFAULT_N_SURROGATES,
    DEFAULT_PE_M,
    DEFAULT_PE_TAU,
    DEFAULT_SPECTRUM_TOLERANCE,
    DEFAULT_TOL,
    IAAFTResult,
    cache_key as iaaft_cache_key,
    clear_iaaft_cache,
    iaaft_surrogate,
    iaaft_test,
    permutation_entropy,
)
from app.services.validation.mbb import (
    BOOTSTRAP_CIRCULAR,
    BOOTSTRAP_STATIONARY,
    DEFAULT_ALPHA as MBB_DEFAULT_ALPHA,
    DEFAULT_N_REPLICATES,
    MBBError,
    MBBResult,
    cache_key as mbb_cache_key,
    clear_mbb_cache,
    mbb_ci,
    mbb_coefficient_ci,
    politis_white_block_length as mbb_optimal_block_length,
)
from app.services.validation.coefficient_ci import (
    DEFAULT_B,
    DEFAULT_Z_THRESHOLD,
    CoefficientCIConfig,
    CoefficientCIError,
    CoefficientCIResult,
    CoefficientCIValidator,
    politis_white_block_length,
    refit_blob,
    stationary_bootstrap,
)
from app.services.validation.coverage import (
    DEFAULT_TIP_FRACTION_THRESHOLD,
    DEFAULT_TIP_MIN_EDITS,
    DEFAULT_TIP_SKEWNESS_THRESHOLD,
    LABEL_CHIP_TOPIC,
    N_SHAPES,
    SHAPES,
    CoverageResult,
    ShapeVocabularyCoverageTracker,
    gini_coefficient,
)
from app.services.validation.diversity import (
    DEFAULT_REGULARISATION,
    KERNEL_DTW_RBF,
    KERNEL_LATENT_EUCLIDEAN,
    KERNEL_SHAPELET_EDIT,
    DiversityError,
    DiversityResult,
    IncrementalDiversityTracker,
    dpp_log_det_diversity,
)
from app.services.validation.conservation_significance import (
    DEFAULT_BOOTSTRAP_B,
    DEFAULT_MMD_PERMUTATIONS,
    DEFAULT_MMD_SUBSAMPLE_CAP,
    ConservationCIResult,
    ConservationConfig,
    ConservationSignificance,
    ConservationSignificanceError,
    MMDResult,
    RatioTestResult,
    conservation_mmd_test,
    conservation_ratio_test,
    conservation_residual_ci,
    conservation_significance,
)
from app.services.validation.tip_engine import (
    DEFAULT_MAX_TIPS_PER_EDIT,
    DEFAULT_MODALITY_SWITCH_AFTER_N,
    DEFAULT_RECENT_SUPPRESSION_WINDOW,
    DEFAULT_RULES_DIR,
    DEGREE_DIRECTING,
    DEGREE_ORIENTING,
    DEGREE_PRESCRIBING,
    MODALITY_CF,
    MODALITY_CONTINGENCY,
    MODALITY_CONTRASTIVE,
    MODALITY_FEATURE_IMPORTANCE,
    TOPIC_LABEL_CHIP,
    TOPIC_SESSION_METRICS,
    TOPIC_TIP_DISMISSED,
    TOPIC_TIP_EMITTED,
    TOPIC_VALIDATION_METRICS,
    Tip,
    TipEngine,
    TipRuleError,
    load_tip_rules,
    safe_eval,
)
from app.services.validation.validity_rate import (
    CF_RESULT_TOPIC,
    DEFAULT_TIP_RATE_THRESHOLD,
    DEFAULT_TIP_WINDOW,
    DEFAULT_TREND_WINDOW_SECONDS,
    CFResultEvent,
    ValidityRateResult,
    ValidityRateTracker,
)
from app.services.validation.mmd_distshift import (
    DEFAULT_PERMUTATIONS,
    KERNEL_RBF_MEDIAN,
    DistShiftResult,
    MMDDistShiftError,
    MMDLinearResult,
    mmd_linear_time,
    mmd_quadratic,
    replace_library_distshift,
)
from app.services.validation.conformal_pid import (
    BandCheckResult,
    ConformalCalibrationError,
    ConformalConfig,
    ConformalPIDValidator,
    Forecaster,
    ValidationResult,
)
from app.services.validation.native_guide import (
    DEFAULT_DTW_BAND,
    DEFAULT_EPS_PER_DIM,
    DEFAULT_PROXIMITY_PERCENTILE,
    DEFAULT_SPARSITY_THRESHOLD,
    METRIC_DTW,
    METRIC_EUCLIDEAN,
    METRIC_L1,
    NativeGuideError,
    NativeGuideResult,
    NativeGuideThresholds,
    compute_nun_distances,
    load_thresholds,
    native_guide_proximity,
    native_guide_sparsity,
    native_guide_validate,
    percentile_rank,
    save_thresholds,
    thresholds_from_distances,
)
from app.services.validation.probe_ir import (
    DEFAULT_MC_SAMPLES,
    DEFAULT_SIGMA,
    METHOD_LINEARISED,
    METHOD_MONTE_CARLO,
    TIER2_DEFAULT_SIGMA,
    ProbeIRResult,
    ProbeMethodError,
    ProbeModel,
    default_sigma_for_op,
    probe_invalidation_rate,
)
from app.services.validation.stationarity import (
    DEFAULT_BREAK_TOLERANCE,
    StationarityError,
    StationarityResult,
    VERDICT_INTRODUCED,
    VERDICT_NONSTATIONARY_PRESERVED,
    VERDICT_REDUCED,
    VERDICT_STATIONARY_PRESERVED,
    VERDICT_UNDETERMINED,
    joint_stationarity_check,
    whiten_residual,
)
from app.services.validation.ynn_plausibility import (
    DEFAULT_CANDIDATE_MULTIPLIER,
    DEFAULT_K,
    YnnConfig,
    YnnIndexError,
    YnnPlausibilityValidator,
    YnnResult,
    keogh_envelope,
    lb_keogh,
)

__all__ = [
    "AdmissibleCFSampler",
    "BOOTSTRAP_CIRCULAR",
    "BOOTSTRAP_STATIONARY",
    "BandCheckResult",
    "CF_RESULT_TOPIC",
    "CFResultEvent",
    "CherryPickingDetector",
    "CherryPickingError",
    "CherryPickingScore",
    "CoefficientCIConfig",
    "CoefficientCIError",
    "CoefficientCIResult",
    "CoefficientCIValidator",
    "ConformalCalibrationError",
    "ConformalConfig",
    "ConformalPIDValidator",
    "ConservationCIResult",
    "ConservationConfig",
    "ConservationSignificance",
    "ConservationSignificanceError",
    "CoverageResult",
    "DEFAULT_B",
    "DEFAULT_BOOTSTRAP_B",
    "DEFAULT_BREAK_TOLERANCE",
    "DEFAULT_CANDIDATE_MULTIPLIER",
    "DEFAULT_DTW_BAND",
    "DEFAULT_EPS_PER_DIM",
    "DEFAULT_K",
    "DEFAULT_MC_SAMPLES",
    "DEFAULT_MAX_ITER",
    "DEFAULT_MAX_TIPS_PER_EDIT",
    "DEFAULT_MIN_ACCEPTED",
    "DEFAULT_MMD_PERMUTATIONS",
    "DEFAULT_MMD_SUBSAMPLE_CAP",
    "DEFAULT_N_REPLICATES",
    "DEFAULT_MODALITY_SWITCH_AFTER_N",
    "DEFAULT_N_SAMPLES",
    "DEFAULT_N_SURROGATES",
    "DEFAULT_PERMUTATIONS",
    "DEFAULT_PE_M",
    "DEFAULT_PE_TAU",
    "DEFAULT_PROXIMITY_PERCENTILE",
    "DEFAULT_RECENT_SUPPRESSION_WINDOW",
    "DEFAULT_REGULARISATION",
    "DEFAULT_RULES_DIR",
    "DEFAULT_SIGMA",
    "DEFAULT_SPARSITY_THRESHOLD",
    "DEFAULT_SPECTRUM_TOLERANCE",
    "DEFAULT_TOL",
    "DEFAULT_TIP_FRACTION_THRESHOLD",
    "DEFAULT_TIP_MIN_EDITS",
    "DEFAULT_TIP_RATE_THRESHOLD",
    "DEFAULT_TIP_SCORE_THRESHOLD",
    "DEFAULT_TIP_SKEWNESS_THRESHOLD",
    "DEFAULT_TIP_WINDOW",
    "DEFAULT_TREND_WINDOW_SECONDS",
    "DEFAULT_UTILITY_WEIGHTS",
    "DEFAULT_Z_THRESHOLD",
    "DEGREE_DIRECTING",
    "DEGREE_ORIENTING",
    "DEGREE_PRESCRIBING",
    "DistShiftResult",
    "DiversityError",
    "DiversityResult",
    "Forecaster",
    "IAAFTResult",
    "IncrementalDiversityTracker",
    "MBBError",
    "MBBResult",
    "MBB_DEFAULT_ALPHA",
    "KERNEL_DTW_RBF",
    "KERNEL_LATENT_EUCLIDEAN",
    "KERNEL_RBF_MEDIAN",
    "KERNEL_SHAPELET_EDIT",
    "MODALITY_CF",
    "MODALITY_CONTINGENCY",
    "MODALITY_CONTRASTIVE",
    "MODALITY_FEATURE_IMPORTANCE",
    "LABEL_CHIP_TOPIC",
    "MMDDistShiftError",
    "MMDLinearResult",
    "MMDResult",
    "N_SHAPES",
    "METHOD_LINEARISED",
    "METHOD_MONTE_CARLO",
    "METRIC_DTW",
    "METRIC_EUCLIDEAN",
    "METRIC_L1",
    "NativeGuideError",
    "NativeGuideResult",
    "NativeGuideThresholds",
    "ProbeIRResult",
    "ProbeMethodError",
    "ProbeModel",
    "RatioTestResult",
    "SHAPES",
    "ShapeVocabularyCoverageTracker",
    "StationarityError",
    "StationarityResult",
    "TOPIC_LABEL_CHIP",
    "TOPIC_SESSION_METRICS",
    "TOPIC_TIP_DISMISSED",
    "TOPIC_TIP_EMITTED",
    "TOPIC_VALIDATION_METRICS",
    "Tip",
    "TipEngine",
    "TipRuleError",
    "UtilityFn",
    "ValidityRateResult",
    "ValidityRateTracker",
    "TIER2_DEFAULT_SIGMA",
    "VERDICT_INTRODUCED",
    "VERDICT_NONSTATIONARY_PRESERVED",
    "VERDICT_REDUCED",
    "VERDICT_STATIONARY_PRESERVED",
    "VERDICT_UNDETERMINED",
    "ValidationResult",
    "YnnConfig",
    "YnnIndexError",
    "YnnPlausibilityValidator",
    "YnnResult",
    "clear_iaaft_cache",
    "clear_mbb_cache",
    "compute_nun_distances",
    "conservation_mmd_test",
    "conservation_ratio_test",
    "conservation_residual_ci",
    "conservation_significance",
    "default_sigma_for_op",
    "default_utility_fn",
    "dpp_log_det_diversity",
    "gini_coefficient",
    "iaaft_cache_key",
    "iaaft_surrogate",
    "iaaft_test",
    "joint_stationarity_check",
    "mbb_cache_key",
    "mbb_ci",
    "mbb_coefficient_ci",
    "mbb_optimal_block_length",
    "load_tip_rules",
    "mmd_linear_time",
    "mmd_quadratic",
    "keogh_envelope",
    "lb_keogh",
    "load_thresholds",
    "native_guide_proximity",
    "native_guide_sparsity",
    "native_guide_validate",
    "percentile_rank",
    "permutation_entropy",
    "politis_white_block_length",
    "probe_invalidation_rate",
    "refit_blob",
    "replace_library_distshift",
    "safe_eval",
    "save_thresholds",
    "stationary_bootstrap",
    "thresholds_from_distances",
    "whiten_residual",
]
