"""IAAFT surrogate test (VAL-030, slow path).

Iterative Amplitude-Adjusted Fourier Transform surrogate generator,
canonical null model for non-stationary nonlinear time series. Run on
demand when the user clicks "Run full validation" — typical cost is 1–3 s
for ``B=500`` surrogates on ``n=10 k`` samples — and answers the precise
question:

    H0: x_edit is generated by a Gaussian linear process with the same
        amplitude distribution and power spectrum as x_orig.

The surrogate matches both the marginal amplitude distribution and the
power spectrum of x_orig; testing against a discriminating statistic
``q(·)`` (default: Bandt-Pompe permutation entropy) gives a permutation
p-value with the Edgington plus-one correction. **This is not a
"plausibility" test** — it specifically tests whether the edit could be
generated by a linear Gaussian process matched to x_orig, which is the
right question only when KS / AD / MMD on the residuals are insufficient
(autocorrelation makes those tests over-reject).

Sources (binding for ``algorithm-auditor``):

  - Schreiber & Schmitz, "Surrogate time series," *Physica D*
    142(3–4):346–382 (2000), DOI:10.1016/S0167-2789(00)00043-9 —
    canonical IAAFT Algorithm 1; this module implements the algorithm
    verbatim.
  - Theiler, Eubank, Longtin, Galdrikian, Farmer, "Testing for
    nonlinearity in time series: the method of surrogate data,"
    *Physica D* 58(1–4):77–94 (1992) — foundational paper.
  - Lancaster, Iatsenko, Pidde, Ticcinelli, Stefanovska, "Surrogate data
    for hypothesis testing of physical systems," *Physics Reports*
    748:1–60 (2018) — modern catalogue (FT, AAFT, IAAFT, twin,
    small-shuffle, pseudo-periodic, multivariate); §2.4 covers the
    convergence criterion implemented here.
  - Bandt & Pompe, "Permutation entropy: a natural complexity measure
    for time series," *Phys. Rev. Lett.* 88:174102 (2002) — default
    discriminating statistic.

Design notes:
  * Caching is by ``cache_key(x_edit, x_orig, n_surrogates, statistic_name)``
    — the SHA-256 of the array bytes plus parameters. Tab-switching does
    not re-run the slow path.
  * The ``statistic`` argument is pluggable so callers can swap in
    correlation dimension, prediction error, or any other summary
    statistic per Lancaster 2018 §3.
"""
from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass
from typing import Any, Callable, Hashable

import numpy as np

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------


DEFAULT_N_SURROGATES = 500
DEFAULT_MAX_ITER = 100
DEFAULT_TOL = 1e-6
DEFAULT_PE_M = 4
DEFAULT_PE_TAU = 1
DEFAULT_SPECTRUM_TOLERANCE = 0.01  # AC: ‖PSD_surr − PSD_orig‖∞ / ‖PSD_orig‖∞ < 0.01


# ---------------------------------------------------------------------------
# DTO
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class IAAFTResult:
    """Outcome of an IAAFT surrogate test.

    Attributes:
        q_edit:                The discriminating statistic on x_edit.
        q_surrogate_mean:      Mean of ``statistic`` across the B surrogate draws.
        q_surrogate_std:       Sample stddev (population, ddof=0) of the surrogate q's.
        p_value:               Two-sided permutation p-value with the
                               Edgington plus-one correction so a perfect-tie
                               observation maps to ``1 / (B + 1)`` rather
                               than 0.
        surrogate_distribution: Tuple of B floats (frozen for the DTO).
        n_surrogates:          B used.
        statistic_name:        Function name of ``statistic`` — used as
                               part of the cache key and surfaced in the UI.
        spectrum_max_abs_err:  Diagnostic: max relative spectrum error
                               of the *first* surrogate against x_orig
                               (``‖PSD_surr − PSD_orig‖∞ / ‖PSD_orig‖∞``).
                               Useful for verifying convergence in CI.
    """

    q_edit: float
    q_surrogate_mean: float
    q_surrogate_std: float
    p_value: float
    surrogate_distribution: tuple[float, ...]
    n_surrogates: int
    statistic_name: str
    spectrum_max_abs_err: float


# ---------------------------------------------------------------------------
# IAAFT surrogate generator (Schreiber & Schmitz 2000 Algorithm 1)
# ---------------------------------------------------------------------------


def iaaft_surrogate(
    x: np.ndarray,
    *,
    max_iter: int = DEFAULT_MAX_ITER,
    tol: float = DEFAULT_TOL,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Generate one IAAFT surrogate of ``x`` per Schreiber & Schmitz 2000.

    Iteratively alternates between
      1. enforcing the target Fourier amplitude spectrum (replace surrogate
         spectrum magnitudes with ``|FFT(x)|``, keep its phases), and
      2. enforcing the target amplitude distribution (rank-replace surrogate
         values with sorted ``x`` at the same ranks),
    until the per-iteration mean-squared change drops below ``tol`` or
    ``max_iter`` is reached. The amplitude-distribution step is exact at
    every iteration (rank-replace is bijective); the spectrum is
    approximate, with monotonic improvement.

    The returned surrogate is **rank-equivalent to** ``x`` — i.e. it is
    a permutation of the sorted values of ``x`` — and its power spectrum
    matches ``|FFT(x)|`` within ``tol`` (typically ≪ 1 % relative max
    error after ~20 iterations).
    """
    if max_iter < 1:
        raise ValueError(f"max_iter must be ≥ 1; got {max_iter}")
    if tol <= 0:
        raise ValueError(f"tol must be > 0; got {tol}")
    arr = np.asarray(x, dtype=np.float64).reshape(-1)
    n = arr.shape[0]
    if n < 4:
        raise ValueError(f"iaaft_surrogate requires ≥ 4 samples; got {n}")

    generator = rng if rng is not None else np.random.default_rng()
    sorted_x = np.sort(arr)
    amplitude_target = np.abs(np.fft.rfft(arr))

    # Random initial permutation — Schreiber-Schmitz §3.
    s = generator.permutation(arr).astype(np.float64, copy=True)
    prev_diff = float("inf")

    for _ in range(max_iter):
        # Step 1: enforce target spectrum (replace magnitudes, keep phases).
        S = np.fft.rfft(s)
        phases = np.angle(S)
        S_new = amplitude_target * np.exp(1j * phases)
        s_spec = np.fft.irfft(S_new, n=n)

        # Step 2: enforce target amplitude distribution via rank-replace.
        # ``np.argsort(np.argsort(s_spec))`` returns the rank of each entry
        # of ``s_spec``; indexing sorted_x by that rank yields a permutation
        # of sorted_x in the same order as s_spec.
        ranks = np.argsort(np.argsort(s_spec))
        s_new = sorted_x[ranks]

        diff = float(np.mean((s_new - s) ** 2))
        if abs(prev_diff - diff) < tol:
            s = s_new
            break
        s = s_new
        prev_diff = diff

    return s


# ---------------------------------------------------------------------------
# Spectrum-error helper (used by tests + the IAAFTResult diagnostic field)
# ---------------------------------------------------------------------------


def _spectrum_max_abs_err(x: np.ndarray, surrogate: np.ndarray) -> float:
    """``‖|FFT(surrogate)| − |FFT(x)|‖∞ / ‖|FFT(x)|‖∞`` per AC."""
    psd_x = np.abs(np.fft.rfft(np.asarray(x, dtype=np.float64).reshape(-1)))
    psd_s = np.abs(np.fft.rfft(np.asarray(surrogate, dtype=np.float64).reshape(-1)))
    denom = float(np.max(np.abs(psd_x)))
    if denom == 0.0:
        return 0.0
    return float(np.max(np.abs(psd_s - psd_x)) / denom)


# ---------------------------------------------------------------------------
# Permutation entropy (Bandt-Pompe 2002, default discriminating statistic)
# ---------------------------------------------------------------------------


def permutation_entropy(
    x: np.ndarray,
    *,
    m: int = DEFAULT_PE_M,
    tau: int = DEFAULT_PE_TAU,
) -> float:
    """Bandt-Pompe 2002 permutation entropy at order ``m``, lag ``tau``.

    For each length-``m`` window stepped by ``tau``, record the rank
    pattern (an ordinal permutation in [0, m!)). The Shannon entropy of
    the empirical distribution over patterns is the permutation entropy
    — units are nats. Returns 0.0 when ``len(x) < m·tau``.

    See Bandt & Pompe 2002 Eq. 1: ``H(m) = −Σ_π p(π) ln p(π)``.
    """
    if m < 2:
        raise ValueError(f"m must be ≥ 2; got {m}")
    if tau < 1:
        raise ValueError(f"tau must be ≥ 1; got {tau}")
    arr = np.asarray(x, dtype=np.float64).reshape(-1)
    n = arr.shape[0]
    window_len = (m - 1) * tau + 1
    if n < window_len:
        return 0.0
    counts: dict[tuple[int, ...], int] = {}
    last = n - (m - 1) * tau
    for i in range(last):
        # ``np.argsort`` on the window gives the permutation pattern.
        window = arr[i : i + (m - 1) * tau + 1 : tau]
        pattern = tuple(int(k) for k in np.argsort(window))
        counts[pattern] = counts.get(pattern, 0) + 1
    total = sum(counts.values())
    if total == 0:
        return 0.0
    probs = np.fromiter(counts.values(), dtype=np.float64) / total
    return float(-np.sum(probs * np.log(probs)))


# ---------------------------------------------------------------------------
# Per-edit cache
# ---------------------------------------------------------------------------


_iaaft_cache: dict[str, IAAFTResult] = {}


def cache_key(
    x_edit: np.ndarray,
    x_orig: np.ndarray,
    n_surrogates: int,
    statistic_name: str,
) -> str:
    """Stable hash for the IAAFT cache.

    SHA-256 over the byte representation of x_edit + x_orig + parameters
    — caller can mutate either array between calls and the cache will
    miss correctly. Cache key is *not* a security primitive; we use
    SHA-256 for collision resistance only.
    """
    arr_e = np.ascontiguousarray(np.asarray(x_edit, dtype=np.float64).reshape(-1))
    arr_o = np.ascontiguousarray(np.asarray(x_orig, dtype=np.float64).reshape(-1))
    h = hashlib.sha256()
    h.update(arr_e.tobytes())
    h.update(b"|orig|")
    h.update(arr_o.tobytes())
    h.update(f"|{int(n_surrogates)}|{statistic_name}".encode())
    return h.hexdigest()


def clear_iaaft_cache() -> None:
    """Drop every cached IAAFT result. Use between sessions or in tests."""
    _iaaft_cache.clear()


# ---------------------------------------------------------------------------
# IAAFT permutation test
# ---------------------------------------------------------------------------


def _surrogate_statistic(
    seed: int,
    x_orig_bytes: bytes,
    x_orig_shape: tuple[int, ...],
    statistic: Callable[[np.ndarray], float],
    max_iter: int,
    tol: float,
) -> float:
    """Worker for the joblib parallel map.

    Receives the original series as raw bytes + shape so it pickles
    cheaply; reconstructs the array, draws an IAAFT surrogate with the
    seeded RNG, and applies ``statistic``.
    """
    x_orig = np.frombuffer(x_orig_bytes, dtype=np.float64).reshape(x_orig_shape)
    surrogate = iaaft_surrogate(
        x_orig,
        max_iter=max_iter,
        tol=tol,
        rng=np.random.default_rng(int(seed)),
    )
    return float(statistic(surrogate))


def iaaft_test(
    x_edit: np.ndarray,
    x_orig: np.ndarray,
    *,
    n_surrogates: int = DEFAULT_N_SURROGATES,
    statistic: Callable[[np.ndarray], float] = permutation_entropy,
    max_iter: int = DEFAULT_MAX_ITER,
    tol: float = DEFAULT_TOL,
    n_jobs: int = -1,
    seed: int = 0,
    use_cache: bool = True,
) -> IAAFTResult:
    """Two-sided IAAFT permutation test of ``x_edit`` against the
    surrogate-of-``x_orig`` null distribution.

    Edgington two-sided plus-one p-value:

        p = (1 + Σ_b 1[|q_b − q̄| ≥ |q_edit − q̄|]) / (B + 1)

    where ``q̄`` is the surrogate mean. The plus-one correction means a
    perfectly tie-breaking observation gets ``1 / (B + 1)`` rather than
    0 (Edgington 1995).

    Returns an ``IAAFTResult``; the surrogate distribution is a tuple of
    floats so the DTO is fully immutable.
    """
    if n_surrogates < 2:
        raise ValueError(f"n_surrogates must be ≥ 2; got {n_surrogates}")

    statistic_name = getattr(statistic, "__name__", repr(statistic))
    key = cache_key(x_edit, x_orig, n_surrogates, statistic_name)
    if use_cache and key in _iaaft_cache:
        return _iaaft_cache[key]

    edit_arr = np.asarray(x_edit, dtype=np.float64).reshape(-1)
    orig_arr = np.asarray(x_orig, dtype=np.float64).reshape(-1)

    q_edit = float(statistic(edit_arr))

    # Spectrum-error diagnostic from a single in-process surrogate.
    diag_rng = np.random.default_rng(int(seed) + 0xD1A6)
    diag_surr = iaaft_surrogate(orig_arr, max_iter=max_iter, tol=tol, rng=diag_rng)
    spectrum_err = _spectrum_max_abs_err(orig_arr, diag_surr)

    rng = np.random.default_rng(int(seed))
    seeds = rng.integers(0, 2 ** 31 - 1, size=n_surrogates).tolist()
    orig_bytes = orig_arr.tobytes()
    orig_shape = orig_arr.shape

    if n_jobs in (0, 1, None):
        surrogate_qs = [
            _surrogate_statistic(int(s), orig_bytes, orig_shape, statistic, max_iter, tol)
            for s in seeds
        ]
    else:
        from joblib import Parallel, delayed  # noqa: PLC0415
        surrogate_qs = Parallel(n_jobs=n_jobs)(
            delayed(_surrogate_statistic)(
                int(s), orig_bytes, orig_shape, statistic, max_iter, tol,
            )
            for s in seeds
        )

    surrogate_qs_arr = np.asarray(surrogate_qs, dtype=np.float64)
    q_mean = float(np.mean(surrogate_qs_arr))
    q_std = float(np.std(surrogate_qs_arr, ddof=0))

    obs_dev = abs(q_edit - q_mean)
    surr_devs = np.abs(surrogate_qs_arr - q_mean)
    extreme_count = int(np.sum(surr_devs >= obs_dev))
    p_value = (1.0 + extreme_count) / (n_surrogates + 1.0)

    result = IAAFTResult(
        q_edit=q_edit,
        q_surrogate_mean=q_mean,
        q_surrogate_std=q_std,
        p_value=float(p_value),
        surrogate_distribution=tuple(float(v) for v in surrogate_qs_arr),
        n_surrogates=int(n_surrogates),
        statistic_name=statistic_name,
        spectrum_max_abs_err=spectrum_err,
    )
    if use_cache:
        _iaaft_cache[key] = result
    return result
