from .noise import (
    amplify as amplify_noise,
    change_color,
    inject_synthetic,
    suppress_denoise,
    whiten,
)
from .cycle import (
    amplify_amplitude,
    change_harmonic_content,
    change_period,
    dampen_amplitude,
    deseasonalise_remove,
    phase_shift,
    replace_with_flat,
)
from .plateau import (
    Tier2OpResult,
    invert,
    raise_lower,
    replace_with_cycle,
    replace_with_trend,
    tilt_detrend,
)
from .spike import (
    amplify,
    clip_cap,
    duplicate as duplicate_spike,
    remove,
    shift_time,
    smear_to_transient,
)
from .step import (
    convert_to_ramp,
    de_jump,
    duplicate,
    invert_sign,
    scale_magnitude,
    shift_in_time,
)
from .transient import (
    amplify as amplify_transient,
    change_decay_constant,
    change_duration,
    convert_to_step,
    dampen,
    duplicate as duplicate_transient,
    remove as remove_transient,
    replace_shape,
    shift_time as shift_time_transient,
)
from .trend import (
    add_acceleration,
    change_slope,
    extrapolate,
    flatten,
    linearise,
    reverse_direction,
)

__all__ = [
    "add_acceleration",
    "amplify_noise",
    "change_color",
    "inject_synthetic",
    "suppress_denoise",
    "whiten",
    "amplify",
    "amplify_transient",
    "change_decay_constant",
    "change_duration",
    "convert_to_step",
    "dampen",
    "duplicate_transient",
    "remove_transient",
    "replace_shape",
    "shift_time_transient",
    "amplify_amplitude",
    "change_harmonic_content",
    "change_period",
    "dampen_amplitude",
    "deseasonalise_remove",
    "phase_shift",
    "replace_with_flat",
    "change_slope",
    "clip_cap",
    "convert_to_ramp",
    "de_jump",
    "duplicate",
    "duplicate_spike",
    "extrapolate",
    "flatten",
    "invert",
    "invert_sign",
    "linearise",
    "raise_lower",
    "remove",
    "replace_with_cycle",
    "replace_with_trend",
    "reverse_direction",
    "scale_magnitude",
    "shift_in_time",
    "shift_time",
    "smear_to_transient",
    "Tier2OpResult",
    "tilt_detrend",
]
