from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[2]
PROJECT_ROOT = BACKEND_DIR.parent
INSTANCE_DIR = BACKEND_DIR / "instance"
BENCHMARK_ROOT = PROJECT_ROOT / "benchmarks"
BENCHMARK_DATASETS_DIR = BENCHMARK_ROOT / "datasets"
BENCHMARK_RAW_DIR = BENCHMARK_ROOT / "raw"
BENCHMARK_MODELS_DIR = BENCHMARK_ROOT / "models"
BENCHMARK_MODEL_REPOS_DIR = BENCHMARK_MODELS_DIR / "repos"
BENCHMARK_MODEL_WEIGHTS_DIR = BENCHMARK_MODELS_DIR / "weights"
BENCHMARK_MODEL_CONFIGS_DIR = BENCHMARK_MODELS_DIR / "configs"
BENCHMARK_MANIFESTS_DIR = BENCHMARK_ROOT / "manifests"
BENCHMARK_DATASETS_MANIFEST_PATH = BENCHMARK_MANIFESTS_DIR / "datasets.json"
BENCHMARK_MODELS_MANIFEST_PATH = BENCHMARK_MANIFESTS_DIR / "models.json"
BENCHMARK_SOURCES_MANIFEST_PATH = BENCHMARK_MANIFESTS_DIR / "sources.json"
